[package]
name = "cr"
version = "0.1.0"
authors = ["Tobias Schottdorf <tobias.schottdorf@gmail.com>"]

[dependencies.protobuf]
git = "https://github.com/stepancheg/rust-protobuf.git"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper"
