[package]
name = "cr"
version = "0.1.0"
authors = ["Tobias Schottdorf <tobias.schottdorf@gmail.com>"]

[dependencies]
protobuf = "1.0.0"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper"
