cockroach:
  image: cockroachdb/cockroach-dev
  # TODO client should speak TLS, remove --insecure.
  command: start --stores=hdd=/data --gossip=self:// --certs=/data --insecure
  expose:
    - "8080"
  volumes:
    - /tmp/test-disk1:/data
rusttest:
  build: .
  links:
    - cockroach
  volumes:
    - target/debug:/work
